// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserManagementApp.UserApi.Data;

#nullable disable

namespace UserManagementApp.UserApi.Migrations
{
    [DbContext(typeof(UserContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserManagementApp.UserApi.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c16aa979-da57-47d3-9ec2-c7dab1dad506"),
                            Age = 21,
                            Gender = (byte)0,
                            Name = "John"
                        },
                        new
                        {
                            Id = new Guid("1b258905-c6d1-428b-ad49-fd5c256fe1e2"),
                            Age = 22,
                            Gender = (byte)1,
                            Name = "Marry"
                        },
                        new
                        {
                            Id = new Guid("6b7501ba-df26-4a9f-bc40-74e6deb02ffc"),
                            Age = 20,
                            Gender = (byte)0,
                            Name = "Gepgre"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
