services:
  users.api:
    image: ${DOCKER_REGISTRY-}user.api
    build:
      context: .
      dockerfile: UserApi/Dockerfile
    ports:
      - "5040:5040"
      - "5041:5041"
    depends_on:
      - users.db
    networks:
      user-net:

  users.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    volumes:
      - users_data:/var/opt/mssql
    networks:
      user-net:
    restart: unless-stopped
    
volumes:
  users_data:

networks:
  user-net:
    driver: bridge
